# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  dev:
    cmds:
      - echo "Starting development server..."
      - echo "Listening on http://localhost:8080/"
      - go run github.com/hajimehoshi/wasmserve@latest ./
    silent: true
