# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

silent: true
tasks:
  dev:
    cmds:
      - echo "Starting development server..."
      - echo "Listening on http://localhost:8080/"
      - go run github.com/hajimehoshi/wasmserve@latest ./src
  build:wasm:
    cmds:
      - echo "Building WASM..."
      - GOOS=js GOARCH=wasm go build -o ./bin/main.wasm ./src

  build:linux:
    desc: Build for Linux. Dependencies https://ebitengine.org/en/documents/install.html?os=linux
    cmds:
      - echo "Building Linux binary..."
      - GOOS=linux GOARCH=amd64 go build -o ./bin/linux-amd64 ./src

  build:windows:
    cmds:
      - echo "Building Windows binary..."
      - GOOS=windows GOARCH=amd64 go build -o ./bin/windows-amd64.exe ./src

  build:
    deps:
      - generate
    cmds:
      - task: build:wasm
      - task: build:linux
      - task: build:windows

  generate:
    preconditions:
      - sh: command -v stringer
        msg: "stringer is not installed. Please install it with 'go install golang.org/x/tools/cmd/stringer@latest'"
    cmds:
      - echo "Generating assets..."
      - go generate -x ./src
