name: Deployment

on:
  push:
    branches: [main]
    paths:
      - "**/*.go"
      - "**/index.html"
      - "/go.*"

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Install stringer
        run: go install golang.org/x/tools/cmd/stringer@latest

      - name: Go generate
        run: task generate

      - name: Build
        run: task build:wasm

      - name: Copy wasm files
        run: cp $(go env GOROOT)/misc/wasm/wasm_exec.js ./bin/wasm/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "bin/wasm"

      - name: Deploy 🚀
        id: deployment
        uses: actions/deploy-pages@v1
